Python:
  beautifiers:
    - Black
    - YAPF
  wrap_line_length: 0
  indent_size: 1
  indent_style: tab
Markdown:
  beautifiers:
    - Prettier
  wrap_line_length: 0
  pragma_insert: !<tag:yaml.org,2002:js/undefined> ''
  pragma_require: !<tag:yaml.org,2002:js/undefined> ''
  wrap_prose: !<tag:yaml.org,2002:js/undefined> ''
